# Общие location для проксирования в Next.js (подключаются в server :80 и :443)
location / {
    proxy_pass http://nextjs;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_cache_bypass $http_upgrade;
}

location /_next/static {
    proxy_pass http://nextjs;
    expires 365d;
    add_header Cache-Control "public, immutable";
}

location /images {
    proxy_pass http://nextjs;
    expires 30d;
    add_header Cache-Control "public";
}

location ~ /\. {
    deny all;
    access_log off;
    log_not_found off;
    return 404;
}
